(() => {
  'use strict'; const Trio=window.Trio, $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function host(){let n=$('trio-agents');if(!n){n=document.createElement('aside');n.id='trio-agents';n.className='agent-drawer';n.hidden=true;document.body.append(n)}return n}
  function label(agent){return agent.live?(agent.busy?'working':'online'):(agent.state||'offline')}
  async function action(id, action, body={}){try{await Trio.api.post(`/api/agents/${encodeURIComponent(id)}/${action}`,body);await refresh()}catch(e){Trio.workspace?.toast?.(e.message||'Agent action failed')}}
  function render(agents=[]){const n=host();n.innerHTML=`<button class="modal-close" aria-label="Close">×</button><h2>Agent roster</h2><button class="new-agent">New agent</button><div class="agent-list">${agents.map(a=>`<article class="agent-card"><b>${esc(a.name)}</b><small>${esc(a.model||a.provider||'agent')} · ${esc(label(a))}</small><p>${esc((a.channels||[]).join(', ')||'No public rooms')}</p><div><button data-action="wake" data-id="${esc(a.id)}">Wake</button><button data-action="hibernate" data-id="${esc(a.id)}">Hibernate</button><button data-action="activity" data-id="${esc(a.id)}">Activity</button></div></article>`).join('')||'<p>No agents.</p>'}</div>`;n.querySelector('.modal-close').onclick=()=>n.hidden=true;n.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>b.dataset.action==='activity'?activity(b.dataset.id):action(b.dataset.id,b.dataset.action));n.querySelector('.new-agent').onclick=create}
  async function refresh(){try{const data=await Trio.api.get('/api/agents');Trio.state.agents=data.agents||[];render(Trio.state.agents)}catch(e){console.warn(e)}}
  async function activity(id){try{const d=await Trio.api.get(`/api/agents/${encodeURIComponent(id)}/activity`);Trio.workspace.modal('Agent activity',`<pre>${esc((d.events||[]).slice(0,20).map(e=>e.content||e.message||JSON.stringify(e)).join('\n')||'No activity')}</pre>`)}catch(e){Trio.workspace.toast(e.message)}}
  async function create(){Trio.workspace.modal('Create agent','<label>Name<input name="name" required></label><label>Provider<select name="provider"><option>codex</option><option>claude</option></select></label><label>Model<input name="model"></label>',async node=>{const f=new FormData(node.querySelector('form'));try{await Trio.api.post('/api/agents',{name:f.get('name'),provider:f.get('provider'),model:f.get('model'),channels:[Trio.state.channel].filter(Boolean)});await refresh()}catch(e){Trio.workspace.toast(e.message||'Could not create agent')}})}
  Trio.agents={init(){refresh();Trio.events.addEventListener('workspace:updated',refresh)},render,refresh,label,action};
})();
